---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
df <- read_csv('data/final.csv')
```

```{r}
colnames(df)
```


```{r}
g <- df %>% filter(slpm > 0, sapm > 0, 
              !is.na(fstyle)) %>% 
  ggplot(aes(td_avg, sub_avg)) +
  geom_point(aes(color=fstyle), size=1.25, alpha=.35) +
  xlim(0, 10) +
  ylim(0, 8) +
  ggtitle('Submission Attempts vs. Takedowns') +
  labs(color='Fighter Style') +
  xlab('Average Takedowns per Fight') +
  ylab('Avgerage \nSubmission \nAttempts\n per Fight') +
  theme(axis.title.y = element_text(angle=0, vjust=.5),
        plot.title = element_text(size=16))

g
```

```{r}
library(viridis)
```

```{r}
ggsave('scatter.png', g, width=8, height=4)
```


```{r}
g <- df %>% filter(td_def > 0, td_def < 1, weight1 > 160, wc != 'shw', 
              !is.na(fstyle)) %>% 
  ggplot(aes(age, active, color=wc)) +
  geom_point(aes(color=wc), size=2.5, alpha=.5) +
  geom_smooth(se=FALSE) +
  facet_wrap('weightclass') +
  xlim(20, 55) +
  ylim(0, 10) +
  ggtitle('Activity Levels by Age and Weight Class') +
  labs(color='Weight Class') +
  xlab('Age (years)') +
  ylab('Total \nStrikes\n per Minute \n(landed +\n absorbed)') +
  theme(axis.title.y = element_text(angle=0, vjust=.5),
        plot.title = element_text(size=16)) +
  guides(color=FALSE) +
  scale_color_discrete()

g
```



```{r}
ggsave('scatter2.png', g, width=8, height=4)
```

